info:
  version 0.1
  title: Tetsuo Configuration API
---
parameters:
  - in: body
    description: The data to send to the API. This data is json format, and describes the application deployment. These map directly to the unit confiugration directives of application name, listener and working directory
    schema:
      type: object
      required:
        - name
        - port
        - directory
      properties:
       name: 
         type: string 
         example: swapi-json-server
       port: 
         type: string 
         example: 80
       directory: 
         type: string 
         example: /apps/swapi-json-server
responses:
  500:
    description: Something went very wrong
  200:
    description: Return whether or not the request was successful
    schema:
      properties:
        repo:
          type: string
          description: The Repository
          default: none
        branch:
          type: string
          description: The Branch
          default: none
        dest:
          type: string
          description: The Destination
          default: none
